In [2]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
matrix1 = np.reshape(mydata,(5,4), order='C')
print(matrix1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [15]:
print(matrix1[2,2])

10


In [17]:
matrix2 = np.reshape(mydata,(5,4), order='F')
print(matrix2)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [20]:
print(matrix2[0,2])

10


In [25]:
#OOP Concept:
mydata.reshape((5,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
r1= ['I', 'am', 'happy']
r2= ["what", 'a', 'day']
r3= [1,2,3]



In [28]:
[r1,r2,r3]

[['I', 'am', 'happy'], ['what', 'a', 'day'], [1, 2, 3]]

In [31]:
print(np.array([r1,r2,r3]))

[['I' 'am' 'happy']
 ['what' 'a' 'day']
 ['1' '2' '3']]
