In [2]:
l = [12, 24, 28, 76, 55, 69, 89, 56]


In [6]:
import numpy as np
a= np.array(l)

In [8]:
a

array([12, 24, 28, 76, 55, 69, 89, 56])

In [13]:
l.pop()

56

In [15]:
l

[12, 24, 28, 76, 55, 69, 89]

In [27]:
b=a.mean()
print(b)

51.125


In [29]:
print(l)

[12, 24, 28, 76, 55, 69, 89]


In [33]:
l[1:]

[24, 28, 76, 55, 69, 89]

In [36]:
l[:3]

[12, 24, 28]

In [38]:
l[::2]

[12, 28, 55, 89]

In [43]:
a

array([12, 24, 28, 76, 55, 69, 89, 56])

In [45]:
a[2:]

array([28, 76, 55, 69, 89, 56])

In [47]:
a[:5]

array([12, 24, 28, 76, 55])

In [48]:
a[::2]

array([12, 28, 55, 89])